### ISSUE TITLE
week_4(day-5)peer-to-peer code review

### ISSUE THREAD

**Issue by gisachris** [MenendezON/Portfolio#11]
Great Job Menendez your project portfolio is looking amazing. According to the figma design there is honestly nothing more to implement the design and functionality are great and the workflow and code base look great as well. keep up the Amazing work!.

**Comment by maryam0007** [comment]
Hey Nelson, as a team we would like to say that you have done a wonderful job. The code is clean, readable and manageable. Keep us the great work.

**Comment by MenendezON** [comment]
Thank you, guys
