### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by peteronyam** [MenendezON/Portfolio#6]
Great job as your design is just so smooth, but I will suggest you try to take a closer look at the figma design in the contact form area to use the exact background image as it is in the figma design👌

**Comment by Danny-imo** [comment]
I suggest that the contact me header should be position below the background image

**Comment by MenendezON** [comment]
> I suggest that the contact me header should be positioned below the background image



> Great job as your design is just so smooth, but I will suggest you try to take a closer look at the figma design in the contact form area to use the exact background image as it is in the figma design👌

Thank you for your suggestion, I take it into account.

**Comment by MenendezON** [comment]
> I suggest that the contact me header should be position below the background image
Wonderful suggestion, I take it into account.
