### ISSUE TITLE
Deployment of this project

### ISSUE THREAD

**Issue by MenendezON** [MenendezON/Portfolio#8]
This issue concerns the deployment of this portfolio project, by:

- Editing the README.md file
- Editing the style.css file
- Editing the index.html file

You can take a look at the deployment at this address :[Portfolio](https://menendezon.github.io/Portfolio/)

**Comment by divinecharlotte** [comment]
# Hello @MenendezON     😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- Descriptive issues ✔️

## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
